[package]
authors = ["sark"]
description = "A simple terminal for rendering ascii in bevy."
edition = "2021"
exclude = ["images/*"]
homepage = "https://github.com/sarkahn/bevy_ascii_terminal"
keywords = ["bevy", "ascii", "terminal", "roguelike", "tilemap"]
license = "MIT"
name = "bevy_ascii_terminal"
readme = "README.md"
repository = "https://github.com/sarkahn/bevy_ascii_terminal"
version = "0.13.0"

[dependencies]
bevy = { version = "0.11", default-features = false, features = ["png", "bevy_render", "bevy_asset", "bevy_sprite"]}
bitflags = "1.3.2"
arrayvec = "0.7.2"
bevy_tiled_camera = { path="../bevy_tiled_camera", version = "0.7.0", optional = true }
sark_grids = { path="../sark_grids_rs", version="0.5.8" }

[dev-dependencies]
bevy_tiled_camera = { path="../bevy_tiled_camera", version = "0.7.0" }
bracket-noise = "0.8.2"
bracket-random = "0.8.2"
rand = "0.8.4"

[dev-dependencies.bevy]
version = "0.11"
default-features = false
features = ["png", "bevy_winit", "bevy_render"]

[target.'cfg(unix)'.dev-dependencies.bevy]
version = "0.11"
default-features = false
features = ["png", "bevy_winit", "bevy_render", "x11"]

[features]
default = ["camera"]
camera = ["dep:bevy_tiled_camera"]
dev = ["bevy/dynamic_linking"]
