[package]
name = "bevy_terminal"
description = "A simple terminal for rendering ascii in bevy."
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
ron = "0.6.4"

[dev-dependencies]
rand = "0.7.3"