[package]
name = "bevy_terminal"
description = "A simple terminal for rendering ascii in bevy."
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.5", default-features = false }
bevy_render = "0.5"
grid = "0.5.0"