[package]
authors = ["sark"]
description = "A simple terminal for rendering ascii in bevy."
edition = "2021"
homepage = "https://github.com/sarkahn/bevy_ascii_terminal"
keywords = ["bevy", "ascii", "terminal", "roguelike", "tilemap"]
license = "MIT"
name = "bevy_ascii_terminal"
readme = "README.md"
repository = "https://github.com/sarkahn/bevy_ascii_terminal"
version = "0.16.0"

[dependencies.bevy]
version = "0.15"
default-features = false
features = ["png", "bevy_render", "bevy_asset", "bevy_sprite", "bevy_window"]

[dev-dependencies.bevy]
version = "0.15"
default-features = false
features = ["bevy_window", "bevy_render", "bevy_winit"]

[dependencies]
enum-ordinalize = "4.3.0"
thiserror = "1.0.56"
flate2 = "1.0"
byteorder = "1"
sark_grids = "0.6"

[dev-dependencies]
fastnoise-lite = "1.1.1"
rand = "0.8.4"
