[package]
authors = ["sark"]
description = "A simple terminal for rendering ascii in bevy."
edition = "2021"
exclude = ["images/*"]
homepage = "https://github.com/sarkahn/bevy_ascii_terminal"
keywords = ["bevy", "ascii", "terminal", "roguelike", "tilemap"]
license = "MIT"
name = "bevy_ascii_terminal"
readme = "README.md"
repository = "https://github.com/sarkahn/bevy_ascii_terminal"
version = "0.16.0"

[dependencies]
enum-ordinalize = "4.3.0"
thiserror = "1.0.56"

[dependencies.bevy]
version = "0.14"
default-features = false
features = ["png", "bevy_render", "bevy_asset", "bevy_sprite"]

[dev-dependencies.bevy]
version = "0.14"
default-features = false
features = ["png", "bevy_winit", "bevy_render", "x11"]

[dev-dependencies]
fastnoise-lite = "1.1.1"
