[package]
authors = ["sark"]
description = "A simple terminal for rendering ascii in bevy."
edition = "2021"
exclude = ["images/*"]
homepage = "https://github.com/sarkahn/bevy_ascii_terminal"
keywords = ["bevy", "ascii", "terminal", "roguelike", "tilemap"]
license = "MIT"
name = "bevy_ascii_terminal"
readme = "README.md"
repository = "https://github.com/sarkahn/bevy_ascii_terminal"
version = "0.10.1"

[dependencies]
bevy = {path="../bevy", version = "0.8.0-dev", default-features = false, features = ["render"]}
sark_grids = {path="../sark_grids_rs", version="0.5.0"}
bitflags = "1.2"
itertools = "0.10.3"
ron = "0.6.4"
anyhow = "1.0.4"
arrayvec = "0.7.2"

[dev-dependencies]
bevy = {path="../bevy", version = "0.8.0-dev", default-features = false, features = ["png", "bevy_winit", "bevy_render"]}
bevy_tiled_camera = {path="../bevy_tiled_camera", version="0.4.0"}
bracket-noise = "0.8.2"
bracket-random = "0.8.2"
rand = "0.8.4"
