[package]
authors = ["sark"]
description = "A simple terminal for rendering ascii in bevy."
edition = "2021"
exclude = ["images/*"]
homepage = "https://github.com/sarkahn/bevy_ascii_terminal"
keywords = ["bevy", "ascii", "terminal", "roguelike", "tilemap"]
license = "MIT"
name = "bevy_ascii_terminal"
readme = "README.md"
repository = "https://github.com/sarkahn/bevy_ascii_terminal"
version = "0.9.1"

[dependencies]
bevy = {version = "0.7", default-features = false, features = ["render"]}
bitflags = "1.2"
itertools = "0.10.3"
ron = "0.6.4"
sark_grids = "0.2.6"

[dev-dependencies]
bevy = {version = "0.7", features = ["png", "bevy_winit", "bevy_render"]}
bevy_tiled_camera = "0.3.1"
bracket-noise = "0.8.2"
bracket-random = "0.8.2"
rand = "0.8.4"
