[package]
name = "bevy_ascii_terminal"
description = "A simple terminal for rendering ascii in bevy."
version = "0.7.6"
authors = ["sark"]
homepage = "https://github.com/sarkahn/bevy_ascii_terminal"
repository = "https://github.com/sarkahn/bevy_ascii_terminal"
license = "MIT"
edition = "2021"
exclude = ["images/*"]
readme = "README.md"
keywords = ["bevy", "ascii", "terminal", "roguelike", "tilemap"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bevy = {version = "0.5", default-features = false, features = ["render"]}
ron = "0.6.4"

[dev-dependencies]
bevy = {version = "0.5", default-features = false, features = ["png", "bevy_winit", "bevy_wgpu"]}
rand = "0.7.3"
bracket-noise = "0.8.2"
bracket-random = "0.8.2"
bevy_tiled_camera = "0.2.3"