[package]
authors = ["sark"]
description = "A simple terminal for rendering ascii in bevy."
edition = "2021"
exclude = ["images/*"]
homepage = "https://github.com/sarkahn/bevy_ascii_terminal"
keywords = ["bevy", "ascii", "terminal", "roguelike", "tilemap"]
license = "MIT"
name = "bevy_ascii_terminal"
readme = "README.md"
repository = "https://github.com/sarkahn/bevy_ascii_terminal"
version = "0.16.0"

[dependencies]
enum-ordinalize = "4.3.0"
itertools = "0.12.1"
thiserror = "1.0.56"

[dependencies.bevy]
version = "0.13"
default-features = false
features = ["png", "bevy_render", "bevy_asset", "bevy_sprite"]

[dev-dependencies.bevy]
version = "0.13"
default-features = false
features = ["png", "bevy_winit", "bevy_render", "dynamic_linking", "x11"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
